server:
  tomcat:
    uri-encoding: UTF-8
  port: 31200

eureka:
  client:
    service-url:
      #指定注册中心的地址
      defaultZone: http://localhost:50101/eureka/
  instance:
    instance:
    #    显示ip
    prefer-ip-address: true
    # status 的名称 ---当前项目的名称
    instance-id: wlzx-service-manage-course

spring:
  # 微服务应用名
  application:
    name: wlzx-service-manage-course
  #mysql数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wlzx_course?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0


# mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 映射xml位置
  #type-aliases-package: net.wanho.po # 别名
  configuration: # mybatis的原生配置
    map-underscore-to-camel-case: true # 开启驼峰命名
    #cache-enabled: false # 不使用缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid  # 主键生成方案
      field-strategy: not_empty  # 列的策略
      db-type: mysql # 数据库类型

# 添加页面参数信息
course-publish:
  siteId: 1
  templateId: 4
  previewUrl: http://www.wlzx.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseView/