server:
  port: ${port:40100}
spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.31.10:9300
  application:
    name: wlzx-service-search
eureka:
  client:
    service-url:
      #指定注册中心的地址
      defaultZone: http://localhost:50101/eureka/
  instance:
    instance:
    #    显示ip
    prefer-ip-address: true
    # status 的名称 ---当前项目的名称
    instance-id: wlzx-service-search
