server:
  tomcat:
    uri-encoding: UTF-8
  port: 40400
spring:
  application:
    name: wlzx-service-ucenter-auth
  datasource:
    url: jdbc:mysql://localhost:3306/wlzx_user?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: ${REDIS_HOST:192.168.31.10}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒

eureka:
  client:
    service-url:
      #指定注册中心的地址
      defaultZone: http://localhost:50101/eureka/
  instance:
    instance:
    #    显示ip
    prefer-ip-address: true
    # status 的名称 ---当前项目的名称
    instance-id: wlzx-service-ucenter-auth

auth:
  tokenValiditySeconds: 1200 #token存储到redis的过期时间
  clientId: wlzxWebApp
  clientSecret: wlzxWebApp
  cookieDomain: wlzx.com
  cookieMaxAge: -1