server:
  tomcat:
    uri-encoding: UTF-8
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wlzx_user?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.31.10
    port: 6379


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 映射xml位置
  type-aliases-package: net.wanho.po # 别名
  configuration: # mybatis的原生配置
    map-underscore-to-camel-case: true # 开启驼峰命名
    cache-enabled: false # 不使用缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid  # 主键生成方案
      field-strategy: not_empty  # 列的策略
      db-type: mysql # 数据库类型


